// Code generated by configtable-gen; DO NOT EDIT.
//
// 源表:角色/z_属性加点_效果.xlsx(列映射 / 校验注解见 proto/pandora/config/v1 的 (excel_col) 等选项)。
// 访问模式移植自旧项目 mmorpg 生成的 TableManager(FindAll/FindById/FindByIds/RandOne/Where/First),
// 差异:无单例、无单表热切换;视图不可变,整批快照原子切换见 store.go。
// 表私有校验与域方法在手写伴生文件 attr_point_effect.go(validateAttrPointEffectRow 等)。

package configtable

import (
	"fmt"
	"math/rand/v2"

	configpb "github.com/luyuancpp/pandora/proto/gen/go/pandora/config/v1"
)

// AttrPointEffectTable 配置表 attr_point_effect(角色/z_属性加点_效果.xlsx)只读视图。
type AttrPointEffectTable struct {
	rows               []*configpb.AttrPointEffectRow
	byID               map[uint32]*configpb.AttrPointEffectRow
	listByAttrPointKey map[string][]*configpb.AttrPointEffectRow // 索引 属性点键
}

// newAttrPointEffectTable 建索引 + 校验:主键与唯一键非零 / 不重复(通用)+ validateAttrPointEffectRow(表私有钩子)。
func newAttrPointEffectTable(data *configpb.AttrPointEffectTableData) (*AttrPointEffectTable, error) {
	rows := data.GetRows()
	t := &AttrPointEffectTable{
		rows:               rows,
		byID:               make(map[uint32]*configpb.AttrPointEffectRow, len(rows)),
		listByAttrPointKey: make(map[string][]*configpb.AttrPointEffectRow),
	}
	for i, row := range rows {
		key := row.GetId()
		if key == 0 {
			return nil, fmt.Errorf("attr_point_effect 第 %d 行主键为 0", i+1)
		}
		if _, dup := t.byID[key]; dup {
			return nil, fmt.Errorf("attr_point_effect 主键重复 %v", key)
		}
		if err := validateAttrPointEffectRow(row); err != nil {
			return nil, fmt.Errorf("attr_point_effect 主键 %v: %w", key, err)
		}
		t.byID[key] = row
		t.listByAttrPointKey[row.GetAttrPointKey()] = append(t.listByAttrPointKey[row.GetAttrPointKey()], row)
	}
	return t, nil
}

// All 全部行(加载序)。只读约定:调用方不得修改返回的切片与行。
func (t *AttrPointEffectTable) All() []*configpb.AttrPointEffectRow { return t.rows }

// ByID 按主键查行。
func (t *AttrPointEffectTable) ByID(key uint32) (*configpb.AttrPointEffectRow, bool) {
	row, ok := t.byID[key]
	return row, ok
}

// Exists 主键是否存在。
func (t *AttrPointEffectTable) Exists(key uint32) bool {
	_, ok := t.byID[key]
	return ok
}

// Count 数据行数。
func (t *AttrPointEffectTable) Count() int { return len(t.rows) }

// ByIDs 批量按主键查行(IN 语义;缺失键跳过,结果按入参序)。
func (t *AttrPointEffectTable) ByIDs(keys []uint32) []*configpb.AttrPointEffectRow {
	result := make([]*configpb.AttrPointEffectRow, 0, len(keys))
	for _, key := range keys {
		if row, ok := t.byID[key]; ok {
			result = append(result, row)
		}
	}
	return result
}

// RandOne 均匀随机取一行(空表返回 false)。
func (t *AttrPointEffectTable) RandOne() (*configpb.AttrPointEffectRow, bool) {
	if len(t.rows) == 0 {
		return nil, false
	}
	return t.rows[rand.IntN(len(t.rows))], true
}

// Where 按谓词过滤(加载序)。
func (t *AttrPointEffectTable) Where(pred func(*configpb.AttrPointEffectRow) bool) []*configpb.AttrPointEffectRow {
	var result []*configpb.AttrPointEffectRow
	for _, row := range t.rows {
		if pred(row) {
			result = append(result, row)
		}
	}
	return result
}

// First 按谓词取首个命中(加载序)。
func (t *AttrPointEffectTable) First(pred func(*configpb.AttrPointEffectRow) bool) (*configpb.AttrPointEffectRow, bool) {
	for _, row := range t.rows {
		if pred(row) {
			return row, true
		}
	}
	return nil, false
}

// ListByAttrPointKey 按 属性点键 查全部行(非唯一索引 / 外键反查;加载序)。
// 只读约定:调用方不得修改返回的切片与行。
func (t *AttrPointEffectTable) ListByAttrPointKey(key string) []*configpb.AttrPointEffectRow {
	return t.listByAttrPointKey[key]
}
