// Code generated by configtable-gen; DO NOT EDIT.
//
// 源表:道具/d_掉落.xlsx(列映射 / 校验注解见 proto/pandora/config/v1 的 (excel_col) 等选项)。
// 访问模式移植自旧项目 mmorpg 生成的 TableManager(FindAll/FindById/FindByIds/RandOne/Where/First),
// 差异:无单例、无单表热切换;视图不可变,整批快照原子切换见 store.go。
// 表私有校验与域方法在手写伴生文件 drop.go(validateDropRow 等)。

package configtable

import (
	"fmt"
	"math/rand/v2"

	configpb "github.com/luyuancpp/pandora/proto/gen/go/pandora/config/v1"
)

// DropTable 配置表 drop(道具/d_掉落.xlsx)只读视图。
type DropTable struct {
	rows               []*configpb.DropRow
	byID               map[uint32]*configpb.DropRow
	listByItemConfigId map[uint32][]*configpb.DropRow // 索引 物品ID
}

// newDropTable 建索引 + 校验:主键与唯一键非零 / 不重复(通用)+ validateDropRow(表私有钩子)。
func newDropTable(data *configpb.DropTableData) (*DropTable, error) {
	rows := data.GetRows()
	t := &DropTable{
		rows:               rows,
		byID:               make(map[uint32]*configpb.DropRow, len(rows)),
		listByItemConfigId: make(map[uint32][]*configpb.DropRow),
	}
	for i, row := range rows {
		key := row.GetId()
		if key == 0 {
			return nil, fmt.Errorf("drop 第 %d 行主键为 0", i+1)
		}
		if _, dup := t.byID[key]; dup {
			return nil, fmt.Errorf("drop 主键重复 %v", key)
		}
		if err := validateDropRow(row); err != nil {
			return nil, fmt.Errorf("drop 主键 %v: %w", key, err)
		}
		t.byID[key] = row
		t.listByItemConfigId[row.GetItemConfigId()] = append(t.listByItemConfigId[row.GetItemConfigId()], row)
	}
	return t, nil
}

// All 全部行(加载序)。只读约定:调用方不得修改返回的切片与行。
func (t *DropTable) All() []*configpb.DropRow { return t.rows }

// ByID 按主键查行。
func (t *DropTable) ByID(key uint32) (*configpb.DropRow, bool) {
	row, ok := t.byID[key]
	return row, ok
}

// Exists 主键是否存在。
func (t *DropTable) Exists(key uint32) bool {
	_, ok := t.byID[key]
	return ok
}

// Count 数据行数。
func (t *DropTable) Count() int { return len(t.rows) }

// ByIDs 批量按主键查行(IN 语义;缺失键跳过,结果按入参序)。
func (t *DropTable) ByIDs(keys []uint32) []*configpb.DropRow {
	result := make([]*configpb.DropRow, 0, len(keys))
	for _, key := range keys {
		if row, ok := t.byID[key]; ok {
			result = append(result, row)
		}
	}
	return result
}

// RandOne 均匀随机取一行(空表返回 false)。
func (t *DropTable) RandOne() (*configpb.DropRow, bool) {
	if len(t.rows) == 0 {
		return nil, false
	}
	return t.rows[rand.IntN(len(t.rows))], true
}

// Where 按谓词过滤(加载序)。
func (t *DropTable) Where(pred func(*configpb.DropRow) bool) []*configpb.DropRow {
	var result []*configpb.DropRow
	for _, row := range t.rows {
		if pred(row) {
			result = append(result, row)
		}
	}
	return result
}

// First 按谓词取首个命中(加载序)。
func (t *DropTable) First(pred func(*configpb.DropRow) bool) (*configpb.DropRow, bool) {
	for _, row := range t.rows {
		if pred(row) {
			return row, true
		}
	}
	return nil, false
}

// ListByItemConfigId 按 物品ID 查全部行(非唯一索引 / 外键反查;加载序)。
// 只读约定:调用方不得修改返回的切片与行。
func (t *DropTable) ListByItemConfigId(key uint32) []*configpb.DropRow {
	return t.listByItemConfigId[key]
}
