// Code generated by configtable-gen; DO NOT EDIT.
//
// 源表:道具/d_装备词条.xlsx(列映射 / 校验注解见 proto/pandora/config/v1 的 (excel_col) 等选项)。
// 访问模式移植自旧项目 mmorpg 生成的 TableManager(FindAll/FindById/FindByIds/RandOne/Where/First),
// 差异:无单例、无单表热切换;视图不可变,整批快照原子切换见 store.go。
// 表私有校验与域方法在手写伴生文件 equipment_affix.go(validateEquipmentAffixRow 等)。

package configtable

import (
	"fmt"
	"math/rand/v2"

	configpb "github.com/luyuancpp/pandora/proto/gen/go/pandora/config/v1"
)

// EquipmentAffixTable 配置表 equipment_affix(道具/d_装备词条.xlsx)只读视图。
type EquipmentAffixTable struct {
	rows         []*configpb.EquipmentAffixRow
	byID         map[uint32]*configpb.EquipmentAffixRow
	listByPoolId map[uint32][]*configpb.EquipmentAffixRow // 索引 词条池ID
	listByAttrId map[uint32][]*configpb.EquipmentAffixRow // 索引 属性ID
}

// newEquipmentAffixTable 建索引 + 校验:主键与唯一键非零 / 不重复(通用)+ validateEquipmentAffixRow(表私有钩子)。
func newEquipmentAffixTable(data *configpb.EquipmentAffixTableData) (*EquipmentAffixTable, error) {
	rows := data.GetRows()
	t := &EquipmentAffixTable{
		rows:         rows,
		byID:         make(map[uint32]*configpb.EquipmentAffixRow, len(rows)),
		listByPoolId: make(map[uint32][]*configpb.EquipmentAffixRow),
		listByAttrId: make(map[uint32][]*configpb.EquipmentAffixRow),
	}
	for i, row := range rows {
		key := row.GetId()
		if key == 0 {
			return nil, fmt.Errorf("equipment_affix 第 %d 行主键为 0", i+1)
		}
		if _, dup := t.byID[key]; dup {
			return nil, fmt.Errorf("equipment_affix 主键重复 %v", key)
		}
		if err := validateEquipmentAffixRow(row); err != nil {
			return nil, fmt.Errorf("equipment_affix 主键 %v: %w", key, err)
		}
		t.byID[key] = row
		t.listByPoolId[row.GetPoolId()] = append(t.listByPoolId[row.GetPoolId()], row)
		t.listByAttrId[row.GetAttrId()] = append(t.listByAttrId[row.GetAttrId()], row)
	}
	return t, nil
}

// All 全部行(加载序)。只读约定:调用方不得修改返回的切片与行。
func (t *EquipmentAffixTable) All() []*configpb.EquipmentAffixRow { return t.rows }

// ByID 按主键查行。
func (t *EquipmentAffixTable) ByID(key uint32) (*configpb.EquipmentAffixRow, bool) {
	row, ok := t.byID[key]
	return row, ok
}

// Exists 主键是否存在。
func (t *EquipmentAffixTable) Exists(key uint32) bool {
	_, ok := t.byID[key]
	return ok
}

// Count 数据行数。
func (t *EquipmentAffixTable) Count() int { return len(t.rows) }

// ByIDs 批量按主键查行(IN 语义;缺失键跳过,结果按入参序)。
func (t *EquipmentAffixTable) ByIDs(keys []uint32) []*configpb.EquipmentAffixRow {
	result := make([]*configpb.EquipmentAffixRow, 0, len(keys))
	for _, key := range keys {
		if row, ok := t.byID[key]; ok {
			result = append(result, row)
		}
	}
	return result
}

// RandOne 均匀随机取一行(空表返回 false)。
func (t *EquipmentAffixTable) RandOne() (*configpb.EquipmentAffixRow, bool) {
	if len(t.rows) == 0 {
		return nil, false
	}
	return t.rows[rand.IntN(len(t.rows))], true
}

// Where 按谓词过滤(加载序)。
func (t *EquipmentAffixTable) Where(pred func(*configpb.EquipmentAffixRow) bool) []*configpb.EquipmentAffixRow {
	var result []*configpb.EquipmentAffixRow
	for _, row := range t.rows {
		if pred(row) {
			result = append(result, row)
		}
	}
	return result
}

// First 按谓词取首个命中(加载序)。
func (t *EquipmentAffixTable) First(pred func(*configpb.EquipmentAffixRow) bool) (*configpb.EquipmentAffixRow, bool) {
	for _, row := range t.rows {
		if pred(row) {
			return row, true
		}
	}
	return nil, false
}

// ListByPoolId 按 词条池ID 查全部行(非唯一索引 / 外键反查;加载序)。
// 只读约定:调用方不得修改返回的切片与行。
func (t *EquipmentAffixTable) ListByPoolId(key uint32) []*configpb.EquipmentAffixRow {
	return t.listByPoolId[key]
}

// ListByAttrId 按 属性ID 查全部行(非唯一索引 / 外键反查;加载序)。
// 只读约定:调用方不得修改返回的切片与行。
func (t *EquipmentAffixTable) ListByAttrId(key uint32) []*configpb.EquipmentAffixRow {
	return t.listByAttrId[key]
}
