// Code generated by configtable-gen; DO NOT EDIT.
//
// 源表:道具/装备属性表.xlsx(列映射 / 校验注解见 proto/pandora/config/v1 的 (excel_col) 等选项)。
// 访问模式移植自旧项目 mmorpg 生成的 TableManager(FindAll/FindById/FindByIds/RandOne/Where/First),
// 差异:无单例、无单表热切换;视图不可变,整批快照原子切换见 store.go。
// 表私有校验与域方法在手写伴生文件 equipment_attr.go(validateEquipmentAttrRow 等)。

package configtable

import (
	"fmt"
	"math/rand/v2"

	configpb "github.com/luyuancpp/pandora/proto/gen/go/pandora/config/v1"
)

// EquipmentAttrTable 配置表 equipment_attr(道具/装备属性表.xlsx)只读视图。
type EquipmentAttrTable struct {
	rows []*configpb.EquipmentAttrRow
	byID map[uint32]*configpb.EquipmentAttrRow
}

// newEquipmentAttrTable 建索引 + 校验:主键与唯一键非零 / 不重复(通用)+ validateEquipmentAttrRow(表私有钩子)。
func newEquipmentAttrTable(data *configpb.EquipmentAttrTableData) (*EquipmentAttrTable, error) {
	rows := data.GetRows()
	t := &EquipmentAttrTable{
		rows: rows,
		byID: make(map[uint32]*configpb.EquipmentAttrRow, len(rows)),
	}
	for i, row := range rows {
		key := row.GetId()
		if key == 0 {
			return nil, fmt.Errorf("equipment_attr 第 %d 行主键为 0", i+1)
		}
		if _, dup := t.byID[key]; dup {
			return nil, fmt.Errorf("equipment_attr 主键重复 %v", key)
		}
		if err := validateEquipmentAttrRow(row); err != nil {
			return nil, fmt.Errorf("equipment_attr 主键 %v: %w", key, err)
		}
		t.byID[key] = row
	}
	return t, nil
}

// All 全部行(加载序)。只读约定:调用方不得修改返回的切片与行。
func (t *EquipmentAttrTable) All() []*configpb.EquipmentAttrRow { return t.rows }

// ByID 按主键查行。
func (t *EquipmentAttrTable) ByID(key uint32) (*configpb.EquipmentAttrRow, bool) {
	row, ok := t.byID[key]
	return row, ok
}

// Exists 主键是否存在。
func (t *EquipmentAttrTable) Exists(key uint32) bool {
	_, ok := t.byID[key]
	return ok
}

// Count 数据行数。
func (t *EquipmentAttrTable) Count() int { return len(t.rows) }

// ByIDs 批量按主键查行(IN 语义;缺失键跳过,结果按入参序)。
func (t *EquipmentAttrTable) ByIDs(keys []uint32) []*configpb.EquipmentAttrRow {
	result := make([]*configpb.EquipmentAttrRow, 0, len(keys))
	for _, key := range keys {
		if row, ok := t.byID[key]; ok {
			result = append(result, row)
		}
	}
	return result
}

// RandOne 均匀随机取一行(空表返回 false)。
func (t *EquipmentAttrTable) RandOne() (*configpb.EquipmentAttrRow, bool) {
	if len(t.rows) == 0 {
		return nil, false
	}
	return t.rows[rand.IntN(len(t.rows))], true
}

// Where 按谓词过滤(加载序)。
func (t *EquipmentAttrTable) Where(pred func(*configpb.EquipmentAttrRow) bool) []*configpb.EquipmentAttrRow {
	var result []*configpb.EquipmentAttrRow
	for _, row := range t.rows {
		if pred(row) {
			result = append(result, row)
		}
	}
	return result
}

// First 按谓词取首个命中(加载序)。
func (t *EquipmentAttrTable) First(pred func(*configpb.EquipmentAttrRow) bool) (*configpb.EquipmentAttrRow, bool) {
	for _, row := range t.rows {
		if pred(row) {
			return row, true
		}
	}
	return nil, false
}
