// Code generated by configtable-gen; DO NOT EDIT.
//
// 配置表 level 的稳定「ID → 位序」映射((excel_bit_index);
// 移植旧项目 bit_index 机制,供进度 / 解锁位图存储用)。
// 稳定性契约:位序一经分配永不变更、永不复用;状态文件
// configtable/bitindex_state/level.json 是权威(git 跟踪,不可手改 / 丢弃)。

package configtable

// levelBitIndexMap 当前表内 ID → 位序(已删除 ID 的位保留但不在此映射)。
var levelBitIndexMap = map[uint32]uint32{
	1:  0,
	2:  1,
	3:  2,
	4:  3,
	5:  4,
	6:  5,
	7:  6,
	9:  7,
	10: 8,
	8:  9,
}

// LevelBitIndex 查 ID 的位序;ID 不在当前表内返回 false。
func LevelBitIndex(id uint32) (uint32, bool) {
	bit, ok := levelBitIndexMap[id]
	return bit, ok
}

// LevelBitCount 位图长度 = 最大已分配位 + 1(含已删除 ID 的保留位,存储侧按此定容)。
const LevelBitCount uint32 = 10
