// Code generated by configtable-gen; DO NOT EDIT.
//
// 源表:任务/r_任务.xlsx(列映射 / 校验注解见 proto/pandora/config/v1 的 (excel_col) 等选项)。
// 访问模式移植自旧项目 mmorpg 生成的 TableManager(FindAll/FindById/FindByIds/RandOne/Where/First),
// 差异:无单例、无单表热切换;视图不可变,整批快照原子切换见 store.go。
// 表私有校验与域方法在手写伴生文件 mission.go(validateMissionRow 等)。

package configtable

import (
	"fmt"
	"math/rand/v2"

	configpb "github.com/luyuancpp/pandora/proto/gen/go/pandora/config/v1"
)

// MissionTable 配置表 mission(任务/r_任务.xlsx)只读视图。
type MissionTable struct {
	rows           []*configpb.MissionRow
	byID           map[uint32]*configpb.MissionRow
	listByRewardId map[uint32][]*configpb.MissionRow // 索引 奖励ID
}

// newMissionTable 建索引 + 校验:主键与唯一键非零 / 不重复(通用)+ validateMissionRow(表私有钩子)。
func newMissionTable(data *configpb.MissionTableData) (*MissionTable, error) {
	rows := data.GetRows()
	t := &MissionTable{
		rows:           rows,
		byID:           make(map[uint32]*configpb.MissionRow, len(rows)),
		listByRewardId: make(map[uint32][]*configpb.MissionRow),
	}
	for i, row := range rows {
		key := row.GetId()
		if key == 0 {
			return nil, fmt.Errorf("mission 第 %d 行主键为 0", i+1)
		}
		if _, dup := t.byID[key]; dup {
			return nil, fmt.Errorf("mission 主键重复 %v", key)
		}
		if err := validateMissionRow(row); err != nil {
			return nil, fmt.Errorf("mission 主键 %v: %w", key, err)
		}
		t.byID[key] = row
		t.listByRewardId[row.GetRewardId()] = append(t.listByRewardId[row.GetRewardId()], row)
	}
	return t, nil
}

// All 全部行(加载序)。只读约定:调用方不得修改返回的切片与行。
func (t *MissionTable) All() []*configpb.MissionRow { return t.rows }

// ByID 按主键查行。
func (t *MissionTable) ByID(key uint32) (*configpb.MissionRow, bool) {
	row, ok := t.byID[key]
	return row, ok
}

// Exists 主键是否存在。
func (t *MissionTable) Exists(key uint32) bool {
	_, ok := t.byID[key]
	return ok
}

// Count 数据行数。
func (t *MissionTable) Count() int { return len(t.rows) }

// ByIDs 批量按主键查行(IN 语义;缺失键跳过,结果按入参序)。
func (t *MissionTable) ByIDs(keys []uint32) []*configpb.MissionRow {
	result := make([]*configpb.MissionRow, 0, len(keys))
	for _, key := range keys {
		if row, ok := t.byID[key]; ok {
			result = append(result, row)
		}
	}
	return result
}

// RandOne 均匀随机取一行(空表返回 false)。
func (t *MissionTable) RandOne() (*configpb.MissionRow, bool) {
	if len(t.rows) == 0 {
		return nil, false
	}
	return t.rows[rand.IntN(len(t.rows))], true
}

// Where 按谓词过滤(加载序)。
func (t *MissionTable) Where(pred func(*configpb.MissionRow) bool) []*configpb.MissionRow {
	var result []*configpb.MissionRow
	for _, row := range t.rows {
		if pred(row) {
			result = append(result, row)
		}
	}
	return result
}

// First 按谓词取首个命中(加载序)。
func (t *MissionTable) First(pred func(*configpb.MissionRow) bool) (*configpb.MissionRow, bool) {
	for _, row := range t.rows {
		if pred(row) {
			return row, true
		}
	}
	return nil, false
}

// ListByRewardId 按 奖励ID 查全部行(非唯一索引 / 外键反查;加载序)。
// 只读约定:调用方不得修改返回的切片与行。
func (t *MissionTable) ListByRewardId(key uint32) []*configpb.MissionRow {
	return t.listByRewardId[key]
}
