// Code generated by configtable-gen; DO NOT EDIT.
//
// 源表:道具/d_商店.xlsx(列映射 / 校验注解见 proto/pandora/config/v1 的 (excel_col) 等选项)。
// 访问模式移植自旧项目 mmorpg 生成的 TableManager(FindAll/FindById/FindByIds/RandOne/Where/First),
// 差异:无单例、无单表热切换;视图不可变,整批快照原子切换见 store.go。
// 表私有校验与域方法在手写伴生文件 shop.go(validateShopRow 等)。

package configtable

import (
	"fmt"
	"math/rand/v2"

	configpb "github.com/luyuancpp/pandora/proto/gen/go/pandora/config/v1"
)

// ShopTable 配置表 shop(道具/d_商店.xlsx)只读视图。
type ShopTable struct {
	rows               []*configpb.ShopRow
	byID               map[uint32]*configpb.ShopRow
	listByShopId       map[uint32][]*configpb.ShopRow // 索引 商店ID
	listByItemConfigId map[uint32][]*configpb.ShopRow // 索引 道具ID
}

// newShopTable 建索引 + 校验:主键与唯一键非零 / 不重复(通用)+ validateShopRow(表私有钩子)。
func newShopTable(data *configpb.ShopTableData) (*ShopTable, error) {
	rows := data.GetRows()
	t := &ShopTable{
		rows:               rows,
		byID:               make(map[uint32]*configpb.ShopRow, len(rows)),
		listByShopId:       make(map[uint32][]*configpb.ShopRow),
		listByItemConfigId: make(map[uint32][]*configpb.ShopRow),
	}
	for i, row := range rows {
		key := row.GetId()
		if key == 0 {
			return nil, fmt.Errorf("shop 第 %d 行主键为 0", i+1)
		}
		if _, dup := t.byID[key]; dup {
			return nil, fmt.Errorf("shop 主键重复 %v", key)
		}
		if err := validateShopRow(row); err != nil {
			return nil, fmt.Errorf("shop 主键 %v: %w", key, err)
		}
		t.byID[key] = row
		t.listByShopId[row.GetShopId()] = append(t.listByShopId[row.GetShopId()], row)
		t.listByItemConfigId[row.GetItemConfigId()] = append(t.listByItemConfigId[row.GetItemConfigId()], row)
	}
	return t, nil
}

// All 全部行(加载序)。只读约定:调用方不得修改返回的切片与行。
func (t *ShopTable) All() []*configpb.ShopRow { return t.rows }

// ByID 按主键查行。
func (t *ShopTable) ByID(key uint32) (*configpb.ShopRow, bool) {
	row, ok := t.byID[key]
	return row, ok
}

// Exists 主键是否存在。
func (t *ShopTable) Exists(key uint32) bool {
	_, ok := t.byID[key]
	return ok
}

// Count 数据行数。
func (t *ShopTable) Count() int { return len(t.rows) }

// ByIDs 批量按主键查行(IN 语义;缺失键跳过,结果按入参序)。
func (t *ShopTable) ByIDs(keys []uint32) []*configpb.ShopRow {
	result := make([]*configpb.ShopRow, 0, len(keys))
	for _, key := range keys {
		if row, ok := t.byID[key]; ok {
			result = append(result, row)
		}
	}
	return result
}

// RandOne 均匀随机取一行(空表返回 false)。
func (t *ShopTable) RandOne() (*configpb.ShopRow, bool) {
	if len(t.rows) == 0 {
		return nil, false
	}
	return t.rows[rand.IntN(len(t.rows))], true
}

// Where 按谓词过滤(加载序)。
func (t *ShopTable) Where(pred func(*configpb.ShopRow) bool) []*configpb.ShopRow {
	var result []*configpb.ShopRow
	for _, row := range t.rows {
		if pred(row) {
			result = append(result, row)
		}
	}
	return result
}

// First 按谓词取首个命中(加载序)。
func (t *ShopTable) First(pred func(*configpb.ShopRow) bool) (*configpb.ShopRow, bool) {
	for _, row := range t.rows {
		if pred(row) {
			return row, true
		}
	}
	return nil, false
}

// ListByShopId 按 商店ID 查全部行(非唯一索引 / 外键反查;加载序)。
// 只读约定:调用方不得修改返回的切片与行。
func (t *ShopTable) ListByShopId(key uint32) []*configpb.ShopRow {
	return t.listByShopId[key]
}

// ListByItemConfigId 按 道具ID 查全部行(非唯一索引 / 外键反查;加载序)。
// 只读约定:调用方不得修改返回的切片与行。
func (t *ShopTable) ListByItemConfigId(key uint32) []*configpb.ShopRow {
	return t.listByItemConfigId[key]
}
