// Code generated by configtable-gen; DO NOT EDIT.
//
// 源表:关卡/s_刷怪点.xlsx(列映射 / 校验注解见 proto/pandora/config/v1 的 (excel_col) 等选项)。
// 访问模式移植自旧项目 mmorpg 生成的 TableManager(FindAll/FindById/FindByIds/RandOne/Where/First),
// 差异:无单例、无单表热切换;视图不可变,整批快照原子切换见 store.go。
// 表私有校验与域方法在手写伴生文件 spawn_point.go(validateSpawnPointRow 等)。

package configtable

import (
	"fmt"
	"math/rand/v2"

	configpb "github.com/luyuancpp/pandora/proto/gen/go/pandora/config/v1"
)

// SpawnPointTable 配置表 spawn_point(关卡/s_刷怪点.xlsx)只读视图。
type SpawnPointTable struct {
	rows               []*configpb.SpawnPointRow
	byID               map[uint32]*configpb.SpawnPointRow
	listBySpawnGroupId map[uint32][]*configpb.SpawnPointRow // 索引 刷怪组Id
	listByLevelId      map[uint32][]*configpb.SpawnPointRow // 索引 关卡Id
}

// newSpawnPointTable 建索引 + 校验:主键与唯一键非零 / 不重复(通用)+ validateSpawnPointRow(表私有钩子)。
func newSpawnPointTable(data *configpb.SpawnPointTableData) (*SpawnPointTable, error) {
	rows := data.GetRows()
	t := &SpawnPointTable{
		rows:               rows,
		byID:               make(map[uint32]*configpb.SpawnPointRow, len(rows)),
		listBySpawnGroupId: make(map[uint32][]*configpb.SpawnPointRow),
		listByLevelId:      make(map[uint32][]*configpb.SpawnPointRow),
	}
	for i, row := range rows {
		key := row.GetId()
		if key == 0 {
			return nil, fmt.Errorf("spawn_point 第 %d 行主键为 0", i+1)
		}
		if _, dup := t.byID[key]; dup {
			return nil, fmt.Errorf("spawn_point 主键重复 %v", key)
		}
		if err := validateSpawnPointRow(row); err != nil {
			return nil, fmt.Errorf("spawn_point 主键 %v: %w", key, err)
		}
		t.byID[key] = row
		t.listBySpawnGroupId[row.GetSpawnGroupId()] = append(t.listBySpawnGroupId[row.GetSpawnGroupId()], row)
		t.listByLevelId[row.GetLevelId()] = append(t.listByLevelId[row.GetLevelId()], row)
	}
	return t, nil
}

// All 全部行(加载序)。只读约定:调用方不得修改返回的切片与行。
func (t *SpawnPointTable) All() []*configpb.SpawnPointRow { return t.rows }

// ByID 按主键查行。
func (t *SpawnPointTable) ByID(key uint32) (*configpb.SpawnPointRow, bool) {
	row, ok := t.byID[key]
	return row, ok
}

// Exists 主键是否存在。
func (t *SpawnPointTable) Exists(key uint32) bool {
	_, ok := t.byID[key]
	return ok
}

// Count 数据行数。
func (t *SpawnPointTable) Count() int { return len(t.rows) }

// ByIDs 批量按主键查行(IN 语义;缺失键跳过,结果按入参序)。
func (t *SpawnPointTable) ByIDs(keys []uint32) []*configpb.SpawnPointRow {
	result := make([]*configpb.SpawnPointRow, 0, len(keys))
	for _, key := range keys {
		if row, ok := t.byID[key]; ok {
			result = append(result, row)
		}
	}
	return result
}

// RandOne 均匀随机取一行(空表返回 false)。
func (t *SpawnPointTable) RandOne() (*configpb.SpawnPointRow, bool) {
	if len(t.rows) == 0 {
		return nil, false
	}
	return t.rows[rand.IntN(len(t.rows))], true
}

// Where 按谓词过滤(加载序)。
func (t *SpawnPointTable) Where(pred func(*configpb.SpawnPointRow) bool) []*configpb.SpawnPointRow {
	var result []*configpb.SpawnPointRow
	for _, row := range t.rows {
		if pred(row) {
			result = append(result, row)
		}
	}
	return result
}

// First 按谓词取首个命中(加载序)。
func (t *SpawnPointTable) First(pred func(*configpb.SpawnPointRow) bool) (*configpb.SpawnPointRow, bool) {
	for _, row := range t.rows {
		if pred(row) {
			return row, true
		}
	}
	return nil, false
}

// ListBySpawnGroupId 按 刷怪组Id 查全部行(非唯一索引 / 外键反查;加载序)。
// 只读约定:调用方不得修改返回的切片与行。
func (t *SpawnPointTable) ListBySpawnGroupId(key uint32) []*configpb.SpawnPointRow {
	return t.listBySpawnGroupId[key]
}

// ListByLevelId 按 关卡Id 查全部行(非唯一索引 / 外键反查;加载序)。
// 只读约定:调用方不得修改返回的切片与行。
func (t *SpawnPointTable) ListByLevelId(key uint32) []*configpb.SpawnPointRow {
	return t.listByLevelId[key]
}
