// Code generated by configtable-gen; DO NOT EDIT.
//
// 批次快照结构与表注册(旧项目 all_table.go 的移植替代):
// 表清单由 proto 描述符驱动(pandora.config.v1 包内打了 (excel_file) 注解的容器,
// 见 excel.proto),加载语义(manifest 驱动 / 全批成功才切换 / 失败保留旧表)统一在 store.go。

package configtable

import (
	"fmt"

	configpb "github.com/luyuancpp/pandora/proto/gen/go/pandora/config/v1"
)

// Tables 一个批次的全部配置表快照(原子切换的最小单位,批内跨表版本一致)。
type Tables struct {
	Version   uint64
	SourceRev string

	// AttrPointEffect 配置表 attr_point_effect(角色/z_属性加点_效果.xlsx)
	AttrPointEffect *AttrPointEffectTable

	// ChestDrop 配置表 chest_drop(道具/d_宝箱掉落.xlsx)
	ChestDrop *ChestDropTable

	// ChestGroup 配置表 chest_group(关卡/s_宝箱组.xlsx)
	ChestGroup *ChestGroupTable

	// ChestPoint 配置表 chest_point(关卡/s_宝箱点.xlsx)
	ChestPoint *ChestPointTable

	// ChestQualityStage 配置表 chest_quality_stage(道具/d_宝箱品质阶段.xlsx)
	ChestQualityStage *ChestQualityStageTable

	// Condition 配置表 condition(任务/r_条件.xlsx)
	Condition *ConditionTable

	// Dialogue 配置表 dialogue(对话/d_对话.xlsx)
	Dialogue *DialogueTable

	// Drop 配置表 drop(道具/d_掉落.xlsx)
	Drop *DropTable

	// EquipmentAffix 配置表 equipment_affix(道具/d_装备词条.xlsx)
	EquipmentAffix *EquipmentAffixTable

	// EquipmentAttr 配置表 equipment_attr(道具/装备属性表.xlsx)
	EquipmentAttr *EquipmentAttrTable

	// GameModule 配置表 game_module(程序/y_游戏模块.xlsx)
	GameModule *GameModuleTable

	// GmCommand 配置表 gm_command(程序/g_Gm.xlsx)
	GmCommand *GmCommandTable

	// Item 配置表 item(道具/d_道具.xlsx)
	Item *ItemTable

	// Level 配置表 level(关卡/g_关卡.xlsx)
	Level *LevelTable

	// Mission 配置表 mission(任务/r_任务.xlsx)
	Mission *MissionTable

	// Particle 配置表 particle(资产/l_粒子.xlsx)
	Particle *ParticleTable

	// PlayerLevelExp 配置表 player_level_exp(角色/j_玩家等级经验.xlsx)
	PlayerLevelExp *PlayerLevelExpTable

	// Reward 配置表 reward(任务/r_奖励.xlsx)
	Reward *RewardTable

	// RoleAttrMap 配置表 role_attr_map(角色/j_角色数值属性映射.xlsx)
	RoleAttrMap *RoleAttrMapTable

	// RoleLevel 配置表 role_level(角色/j_角色等级.xlsx)
	RoleLevel *RoleLevelTable

	// Role 配置表 role(角色/j_角色配置表.xlsx)
	Role *RoleTable

	// Shop 配置表 shop(道具/d_商店.xlsx)
	Shop *ShopTable

	// SkillBullet 配置表 skill_bullet(技能/j_技能_方位类型_子弹.xlsx)
	SkillBullet *SkillBulletTable

	// SkillCardEffect 配置表 skill_card_effect(技能/j_技能卡_效果.xlsx)
	SkillCardEffect *SkillCardEffectTable

	// SkillCard 配置表 skill_card(技能/j_技能卡.xlsx)
	SkillCard *SkillCardTable

	// SkillCardUpgrade 配置表 skill_card_upgrade(技能/j_技能卡升级.xlsx)
	SkillCardUpgrade *SkillCardUpgradeTable

	// SkillCircle 配置表 skill_circle(技能/j_技能_方位类型_圆形.xlsx)
	SkillCircle *SkillCircleTable

	// SkillRect 配置表 skill_rect(技能/j_技能_方位类型_矩形.xlsx)
	SkillRect *SkillRectTable

	// SkillSector 配置表 skill_sector(技能/j_技能_方位类型_扇形.xlsx)
	SkillSector *SkillSectorTable

	// Skill 配置表 skill(技能/j_技能.xlsx)
	Skill *SkillTable

	// SpawnGroup 配置表 spawn_group(关卡/s_刷怪组.xlsx)
	SpawnGroup *SpawnGroupTable

	// SpawnPoint 配置表 spawn_point(关卡/s_刷怪点.xlsx)
	SpawnPoint *SpawnPointTable

	// TalentEffect 配置表 talent_effect(角色/z_专精_效果.xlsx)
	TalentEffect *TalentEffectTable

	// Talent 配置表 talent(角色/z_专精.xlsx)
	Talent *TalentTable

	// Weapon 配置表 weapon(武器/w_武器配置.xlsx)
	Weapon *WeaponTable
}

// specByName 清单表名 → 解析构建注册(Store.Load 消费)。
var specByName = map[string]tableSpec{
	"attr_point_effect":   {protoName: "pandora.config.v1.AttrPointEffectTableData", build: buildAttrPointEffectTable},
	"chest_drop":          {protoName: "pandora.config.v1.ChestDropTableData", build: buildChestDropTable},
	"chest_group":         {protoName: "pandora.config.v1.ChestGroupTableData", build: buildChestGroupTable},
	"chest_point":         {protoName: "pandora.config.v1.ChestPointTableData", build: buildChestPointTable},
	"chest_quality_stage": {protoName: "pandora.config.v1.ChestQualityStageTableData", build: buildChestQualityStageTable},
	"condition":           {protoName: "pandora.config.v1.ConditionTableData", build: buildConditionTable},
	"dialogue":            {protoName: "pandora.config.v1.DialogueTableData", build: buildDialogueTable},
	"drop":                {protoName: "pandora.config.v1.DropTableData", build: buildDropTable},
	"equipment_affix":     {protoName: "pandora.config.v1.EquipmentAffixTableData", build: buildEquipmentAffixTable},
	"equipment_attr":      {protoName: "pandora.config.v1.EquipmentAttrTableData", build: buildEquipmentAttrTable},
	"game_module":         {protoName: "pandora.config.v1.GameModuleTableData", build: buildGameModuleTable},
	"gm_command":          {protoName: "pandora.config.v1.GmCommandTableData", build: buildGmCommandTable},
	"item":                {protoName: "pandora.config.v1.ItemTableData", build: buildItemTable},
	"level":               {protoName: "pandora.config.v1.LevelTableData", build: buildLevelTable},
	"mission":             {protoName: "pandora.config.v1.MissionTableData", build: buildMissionTable},
	"particle":            {protoName: "pandora.config.v1.ParticleTableData", build: buildParticleTable},
	"player_level_exp":    {protoName: "pandora.config.v1.PlayerLevelExpTableData", build: buildPlayerLevelExpTable},
	"reward":              {protoName: "pandora.config.v1.RewardTableData", build: buildRewardTable},
	"role_attr_map":       {protoName: "pandora.config.v1.RoleAttrMapTableData", build: buildRoleAttrMapTable},
	"role_level":          {protoName: "pandora.config.v1.RoleLevelTableData", build: buildRoleLevelTable},
	"role":                {protoName: "pandora.config.v1.RoleTableData", build: buildRoleTable},
	"shop":                {protoName: "pandora.config.v1.ShopTableData", build: buildShopTable},
	"skill_bullet":        {protoName: "pandora.config.v1.SkillBulletTableData", build: buildSkillBulletTable},
	"skill_card_effect":   {protoName: "pandora.config.v1.SkillCardEffectTableData", build: buildSkillCardEffectTable},
	"skill_card":          {protoName: "pandora.config.v1.SkillCardTableData", build: buildSkillCardTable},
	"skill_card_upgrade":  {protoName: "pandora.config.v1.SkillCardUpgradeTableData", build: buildSkillCardUpgradeTable},
	"skill_circle":        {protoName: "pandora.config.v1.SkillCircleTableData", build: buildSkillCircleTable},
	"skill_rect":          {protoName: "pandora.config.v1.SkillRectTableData", build: buildSkillRectTable},
	"skill_sector":        {protoName: "pandora.config.v1.SkillSectorTableData", build: buildSkillSectorTable},
	"skill":               {protoName: "pandora.config.v1.SkillTableData", build: buildSkillTable},
	"spawn_group":         {protoName: "pandora.config.v1.SpawnGroupTableData", build: buildSpawnGroupTable},
	"spawn_point":         {protoName: "pandora.config.v1.SpawnPointTableData", build: buildSpawnPointTable},
	"talent_effect":       {protoName: "pandora.config.v1.TalentEffectTableData", build: buildTalentEffectTable},
	"talent":              {protoName: "pandora.config.v1.TalentTableData", build: buildTalentTable},
	"weapon":              {protoName: "pandora.config.v1.WeaponTableData", build: buildWeaponTable},
}

// validateCrossTables 批内跨表引用完整性((excel_fk);生成阶段已校验,
// 服务端加载再 fail-closed 兜底,全过才允许整批切换)。
func validateCrossTables(dst *Tables) error {
	for _, row := range dst.ChestDrop.All() {
		v := row.GetItemConfigId()
		if v == 0 {
			continue // 0 = 无引用
		}
		if !dst.Item.Exists(v) {
			return fmt.Errorf("表 chest_drop 主键 %d 的 物品ID(%d)在表 item 中不存在", row.GetId(), v)
		}
	}
	for _, row := range dst.ChestGroup.All() {
		v := row.GetLevelId()
		if v == 0 {
			return fmt.Errorf("表 chest_group 主键 %d 的 关卡Id 为 0(必填外键)", row.GetId())
		}
		if !dst.Level.Exists(v) {
			return fmt.Errorf("表 chest_group 主键 %d 的 关卡Id(%d)在表 level 中不存在", row.GetId(), v)
		}
	}
	for _, row := range dst.ChestPoint.All() {
		v := row.GetChestGroupId()
		if v == 0 {
			return fmt.Errorf("表 chest_point 主键 %d 的 宝箱组Id 为 0(必填外键)", row.GetId())
		}
		if !dst.ChestGroup.Exists(v) {
			return fmt.Errorf("表 chest_point 主键 %d 的 宝箱组Id(%d)在表 chest_group 中不存在", row.GetId(), v)
		}
	}
	for _, row := range dst.ChestPoint.All() {
		v := row.GetLevelId()
		if v == 0 {
			return fmt.Errorf("表 chest_point 主键 %d 的 关卡Id 为 0(必填外键)", row.GetId())
		}
		if !dst.Level.Exists(v) {
			return fmt.Errorf("表 chest_point 主键 %d 的 关卡Id(%d)在表 level 中不存在", row.GetId(), v)
		}
	}
	for _, row := range dst.Drop.All() {
		v := row.GetItemConfigId()
		if v == 0 {
			continue // 0 = 无引用
		}
		if !dst.Item.Exists(v) {
			return fmt.Errorf("表 drop 主键 %d 的 物品ID(%d)在表 item 中不存在", row.GetId(), v)
		}
	}
	for _, row := range dst.EquipmentAffix.All() {
		v := row.GetAttrId()
		if v == 0 {
			return fmt.Errorf("表 equipment_affix 主键 %d 的 属性ID 为 0(必填外键)", row.GetId())
		}
		if !dst.RoleAttrMap.Exists(v) {
			return fmt.Errorf("表 equipment_affix 主键 %d 的 属性ID(%d)在表 role_attr_map 中不存在", row.GetId(), v)
		}
	}
	for _, row := range dst.Mission.All() {
		v := row.GetRewardId()
		if v == 0 {
			continue // 0 = 无引用
		}
		if !dst.Reward.Exists(v) {
			return fmt.Errorf("表 mission 主键 %d 的 奖励ID(%d)在表 reward 中不存在", row.GetId(), v)
		}
	}
	for _, row := range dst.RoleLevel.All() {
		v := row.GetRoleId()
		if v == 0 {
			return fmt.Errorf("表 role_level 主键 %d 的 角色ID 为 0(必填外键)", row.GetId())
		}
		if !dst.Role.Exists(v) {
			return fmt.Errorf("表 role_level 主键 %d 的 角色ID(%d)在表 role 中不存在", row.GetId(), v)
		}
	}
	for _, row := range dst.Shop.All() {
		v := row.GetItemConfigId()
		if v == 0 {
			return fmt.Errorf("表 shop 主键 %d 的 道具ID 为 0(必填外键)", row.GetId())
		}
		if !dst.Item.Exists(v) {
			return fmt.Errorf("表 shop 主键 %d 的 道具ID(%d)在表 item 中不存在", row.GetId(), v)
		}
	}
	for _, row := range dst.SkillCardEffect.All() {
		v := row.GetCardId()
		if v == 0 {
			return fmt.Errorf("表 skill_card_effect 主键 %d 的 技能卡ID 为 0(必填外键)", row.GetId())
		}
		if !dst.SkillCard.Exists(v) {
			return fmt.Errorf("表 skill_card_effect 主键 %d 的 技能卡ID(%d)在表 skill_card 中不存在", row.GetId(), v)
		}
	}
	for _, row := range dst.SkillCard.All() {
		v := row.GetSkillId()
		if v == 0 {
			return fmt.Errorf("表 skill_card 主键 %d 的 技能ID 为 0(必填外键)", row.GetId())
		}
		if !dst.Skill.Exists(v) {
			return fmt.Errorf("表 skill_card 主键 %d 的 技能ID(%d)在表 skill 中不存在", row.GetId(), v)
		}
	}
	for _, row := range dst.SpawnGroup.All() {
		v := row.GetLevelId()
		if v == 0 {
			return fmt.Errorf("表 spawn_group 主键 %d 的 关卡Id 为 0(必填外键)", row.GetId())
		}
		if !dst.Level.Exists(v) {
			return fmt.Errorf("表 spawn_group 主键 %d 的 关卡Id(%d)在表 level 中不存在", row.GetId(), v)
		}
	}
	for _, row := range dst.SpawnPoint.All() {
		v := row.GetSpawnGroupId()
		if v == 0 {
			return fmt.Errorf("表 spawn_point 主键 %d 的 刷怪组Id 为 0(必填外键)", row.GetId())
		}
		if !dst.SpawnGroup.Exists(v) {
			return fmt.Errorf("表 spawn_point 主键 %d 的 刷怪组Id(%d)在表 spawn_group 中不存在", row.GetId(), v)
		}
	}
	for _, row := range dst.SpawnPoint.All() {
		v := row.GetLevelId()
		if v == 0 {
			return fmt.Errorf("表 spawn_point 主键 %d 的 关卡Id 为 0(必填外键)", row.GetId())
		}
		if !dst.Level.Exists(v) {
			return fmt.Errorf("表 spawn_point 主键 %d 的 关卡Id(%d)在表 level 中不存在", row.GetId(), v)
		}
	}
	for _, row := range dst.TalentEffect.All() {
		v := row.GetTalentId()
		if v == 0 {
			return fmt.Errorf("表 talent_effect 主键 %d 的 专精ID 为 0(必填外键)", row.GetId())
		}
		if !dst.Talent.Exists(v) {
			return fmt.Errorf("表 talent_effect 主键 %d 的 专精ID(%d)在表 talent 中不存在", row.GetId(), v)
		}
	}
	return nil
}

// ChestDropItemConfigIdRow 解析 chest_drop.物品ID → item 行(外键正查)。
func (tb *Tables) ChestDropItemConfigIdRow(row *configpb.ChestDropRow) (*configpb.ItemRow, bool) {
	return tb.Item.ByID(row.GetItemConfigId())
}

// ChestDropItemConfigIdRowByID 按 chest_drop 主键取行再解析 物品ID → item 行。
func (tb *Tables) ChestDropItemConfigIdRowByID(id uint32) (*configpb.ItemRow, bool) {
	row, ok := tb.ChestDrop.ByID(id)
	if !ok {
		return nil, false
	}
	return tb.ChestDropItemConfigIdRow(row)
}

// ChestGroupLevelIdRow 解析 chest_group.关卡Id → level 行(外键正查)。
func (tb *Tables) ChestGroupLevelIdRow(row *configpb.ChestGroupRow) (*configpb.LevelRow, bool) {
	return tb.Level.ByID(row.GetLevelId())
}

// ChestGroupLevelIdRowByID 按 chest_group 主键取行再解析 关卡Id → level 行。
func (tb *Tables) ChestGroupLevelIdRowByID(id uint32) (*configpb.LevelRow, bool) {
	row, ok := tb.ChestGroup.ByID(id)
	if !ok {
		return nil, false
	}
	return tb.ChestGroupLevelIdRow(row)
}

// ChestPointChestGroupIdRow 解析 chest_point.宝箱组Id → chest_group 行(外键正查)。
func (tb *Tables) ChestPointChestGroupIdRow(row *configpb.ChestPointRow) (*configpb.ChestGroupRow, bool) {
	return tb.ChestGroup.ByID(row.GetChestGroupId())
}

// ChestPointChestGroupIdRowByID 按 chest_point 主键取行再解析 宝箱组Id → chest_group 行。
func (tb *Tables) ChestPointChestGroupIdRowByID(id uint32) (*configpb.ChestGroupRow, bool) {
	row, ok := tb.ChestPoint.ByID(id)
	if !ok {
		return nil, false
	}
	return tb.ChestPointChestGroupIdRow(row)
}

// ChestPointLevelIdRow 解析 chest_point.关卡Id → level 行(外键正查)。
func (tb *Tables) ChestPointLevelIdRow(row *configpb.ChestPointRow) (*configpb.LevelRow, bool) {
	return tb.Level.ByID(row.GetLevelId())
}

// ChestPointLevelIdRowByID 按 chest_point 主键取行再解析 关卡Id → level 行。
func (tb *Tables) ChestPointLevelIdRowByID(id uint32) (*configpb.LevelRow, bool) {
	row, ok := tb.ChestPoint.ByID(id)
	if !ok {
		return nil, false
	}
	return tb.ChestPointLevelIdRow(row)
}

// DropItemConfigIdRow 解析 drop.物品ID → item 行(外键正查)。
func (tb *Tables) DropItemConfigIdRow(row *configpb.DropRow) (*configpb.ItemRow, bool) {
	return tb.Item.ByID(row.GetItemConfigId())
}

// DropItemConfigIdRowByID 按 drop 主键取行再解析 物品ID → item 行。
func (tb *Tables) DropItemConfigIdRowByID(id uint32) (*configpb.ItemRow, bool) {
	row, ok := tb.Drop.ByID(id)
	if !ok {
		return nil, false
	}
	return tb.DropItemConfigIdRow(row)
}

// EquipmentAffixAttrIdRow 解析 equipment_affix.属性ID → role_attr_map 行(外键正查)。
func (tb *Tables) EquipmentAffixAttrIdRow(row *configpb.EquipmentAffixRow) (*configpb.RoleAttrMapRow, bool) {
	return tb.RoleAttrMap.ByID(row.GetAttrId())
}

// EquipmentAffixAttrIdRowByID 按 equipment_affix 主键取行再解析 属性ID → role_attr_map 行。
func (tb *Tables) EquipmentAffixAttrIdRowByID(id uint32) (*configpb.RoleAttrMapRow, bool) {
	row, ok := tb.EquipmentAffix.ByID(id)
	if !ok {
		return nil, false
	}
	return tb.EquipmentAffixAttrIdRow(row)
}

// MissionRewardIdRow 解析 mission.奖励ID → reward 行(外键正查)。
func (tb *Tables) MissionRewardIdRow(row *configpb.MissionRow) (*configpb.RewardRow, bool) {
	return tb.Reward.ByID(row.GetRewardId())
}

// MissionRewardIdRowByID 按 mission 主键取行再解析 奖励ID → reward 行。
func (tb *Tables) MissionRewardIdRowByID(id uint32) (*configpb.RewardRow, bool) {
	row, ok := tb.Mission.ByID(id)
	if !ok {
		return nil, false
	}
	return tb.MissionRewardIdRow(row)
}

// RoleLevelRoleIdRow 解析 role_level.角色ID → role 行(外键正查)。
func (tb *Tables) RoleLevelRoleIdRow(row *configpb.RoleLevelRow) (*configpb.RoleRow, bool) {
	return tb.Role.ByID(row.GetRoleId())
}

// RoleLevelRoleIdRowByID 按 role_level 主键取行再解析 角色ID → role 行。
func (tb *Tables) RoleLevelRoleIdRowByID(id uint32) (*configpb.RoleRow, bool) {
	row, ok := tb.RoleLevel.ByID(id)
	if !ok {
		return nil, false
	}
	return tb.RoleLevelRoleIdRow(row)
}

// ShopItemConfigIdRow 解析 shop.道具ID → item 行(外键正查)。
func (tb *Tables) ShopItemConfigIdRow(row *configpb.ShopRow) (*configpb.ItemRow, bool) {
	return tb.Item.ByID(row.GetItemConfigId())
}

// ShopItemConfigIdRowByID 按 shop 主键取行再解析 道具ID → item 行。
func (tb *Tables) ShopItemConfigIdRowByID(id uint32) (*configpb.ItemRow, bool) {
	row, ok := tb.Shop.ByID(id)
	if !ok {
		return nil, false
	}
	return tb.ShopItemConfigIdRow(row)
}

// SkillCardEffectCardIdRow 解析 skill_card_effect.技能卡ID → skill_card 行(外键正查)。
func (tb *Tables) SkillCardEffectCardIdRow(row *configpb.SkillCardEffectRow) (*configpb.SkillCardRow, bool) {
	return tb.SkillCard.ByID(row.GetCardId())
}

// SkillCardEffectCardIdRowByID 按 skill_card_effect 主键取行再解析 技能卡ID → skill_card 行。
func (tb *Tables) SkillCardEffectCardIdRowByID(id uint32) (*configpb.SkillCardRow, bool) {
	row, ok := tb.SkillCardEffect.ByID(id)
	if !ok {
		return nil, false
	}
	return tb.SkillCardEffectCardIdRow(row)
}

// SkillCardSkillIdRow 解析 skill_card.技能ID → skill 行(外键正查)。
func (tb *Tables) SkillCardSkillIdRow(row *configpb.SkillCardRow) (*configpb.SkillRow, bool) {
	return tb.Skill.ByID(row.GetSkillId())
}

// SkillCardSkillIdRowByID 按 skill_card 主键取行再解析 技能ID → skill 行。
func (tb *Tables) SkillCardSkillIdRowByID(id uint32) (*configpb.SkillRow, bool) {
	row, ok := tb.SkillCard.ByID(id)
	if !ok {
		return nil, false
	}
	return tb.SkillCardSkillIdRow(row)
}

// SpawnGroupLevelIdRow 解析 spawn_group.关卡Id → level 行(外键正查)。
func (tb *Tables) SpawnGroupLevelIdRow(row *configpb.SpawnGroupRow) (*configpb.LevelRow, bool) {
	return tb.Level.ByID(row.GetLevelId())
}

// SpawnGroupLevelIdRowByID 按 spawn_group 主键取行再解析 关卡Id → level 行。
func (tb *Tables) SpawnGroupLevelIdRowByID(id uint32) (*configpb.LevelRow, bool) {
	row, ok := tb.SpawnGroup.ByID(id)
	if !ok {
		return nil, false
	}
	return tb.SpawnGroupLevelIdRow(row)
}

// SpawnPointSpawnGroupIdRow 解析 spawn_point.刷怪组Id → spawn_group 行(外键正查)。
func (tb *Tables) SpawnPointSpawnGroupIdRow(row *configpb.SpawnPointRow) (*configpb.SpawnGroupRow, bool) {
	return tb.SpawnGroup.ByID(row.GetSpawnGroupId())
}

// SpawnPointSpawnGroupIdRowByID 按 spawn_point 主键取行再解析 刷怪组Id → spawn_group 行。
func (tb *Tables) SpawnPointSpawnGroupIdRowByID(id uint32) (*configpb.SpawnGroupRow, bool) {
	row, ok := tb.SpawnPoint.ByID(id)
	if !ok {
		return nil, false
	}
	return tb.SpawnPointSpawnGroupIdRow(row)
}

// SpawnPointLevelIdRow 解析 spawn_point.关卡Id → level 行(外键正查)。
func (tb *Tables) SpawnPointLevelIdRow(row *configpb.SpawnPointRow) (*configpb.LevelRow, bool) {
	return tb.Level.ByID(row.GetLevelId())
}

// SpawnPointLevelIdRowByID 按 spawn_point 主键取行再解析 关卡Id → level 行。
func (tb *Tables) SpawnPointLevelIdRowByID(id uint32) (*configpb.LevelRow, bool) {
	row, ok := tb.SpawnPoint.ByID(id)
	if !ok {
		return nil, false
	}
	return tb.SpawnPointLevelIdRow(row)
}

// TalentEffectTalentIdRow 解析 talent_effect.专精ID → talent 行(外键正查)。
func (tb *Tables) TalentEffectTalentIdRow(row *configpb.TalentEffectRow) (*configpb.TalentRow, bool) {
	return tb.Talent.ByID(row.GetTalentId())
}

// TalentEffectTalentIdRowByID 按 talent_effect 主键取行再解析 专精ID → talent 行。
func (tb *Tables) TalentEffectTalentIdRowByID(id uint32) (*configpb.TalentRow, bool) {
	row, ok := tb.TalentEffect.ByID(id)
	if !ok {
		return nil, false
	}
	return tb.TalentEffectTalentIdRow(row)
}

func buildAttrPointEffectTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.AttrPointEffectTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 attr_point_effect 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 attr_point_effect 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newAttrPointEffectTable(&data)
	if err != nil {
		return err
	}
	dst.AttrPointEffect = t
	return nil
}

func buildChestDropTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.ChestDropTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 chest_drop 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 chest_drop 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newChestDropTable(&data)
	if err != nil {
		return err
	}
	dst.ChestDrop = t
	return nil
}

func buildChestGroupTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.ChestGroupTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 chest_group 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 chest_group 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newChestGroupTable(&data)
	if err != nil {
		return err
	}
	dst.ChestGroup = t
	return nil
}

func buildChestPointTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.ChestPointTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 chest_point 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 chest_point 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newChestPointTable(&data)
	if err != nil {
		return err
	}
	dst.ChestPoint = t
	return nil
}

func buildChestQualityStageTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.ChestQualityStageTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 chest_quality_stage 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 chest_quality_stage 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newChestQualityStageTable(&data)
	if err != nil {
		return err
	}
	dst.ChestQualityStage = t
	return nil
}

func buildConditionTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.ConditionTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 condition 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 condition 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newConditionTable(&data)
	if err != nil {
		return err
	}
	dst.Condition = t
	return nil
}

func buildDialogueTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.DialogueTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 dialogue 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 dialogue 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newDialogueTable(&data)
	if err != nil {
		return err
	}
	dst.Dialogue = t
	return nil
}

func buildDropTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.DropTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 drop 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 drop 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newDropTable(&data)
	if err != nil {
		return err
	}
	dst.Drop = t
	return nil
}

func buildEquipmentAffixTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.EquipmentAffixTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 equipment_affix 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 equipment_affix 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newEquipmentAffixTable(&data)
	if err != nil {
		return err
	}
	dst.EquipmentAffix = t
	return nil
}

func buildEquipmentAttrTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.EquipmentAttrTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 equipment_attr 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 equipment_attr 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newEquipmentAttrTable(&data)
	if err != nil {
		return err
	}
	dst.EquipmentAttr = t
	return nil
}

func buildGameModuleTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.GameModuleTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 game_module 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 game_module 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newGameModuleTable(&data)
	if err != nil {
		return err
	}
	dst.GameModule = t
	return nil
}

func buildGmCommandTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.GmCommandTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 gm_command 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 gm_command 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newGmCommandTable(&data)
	if err != nil {
		return err
	}
	dst.GmCommand = t
	return nil
}

func buildItemTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.ItemTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 item 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 item 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newItemTable(&data)
	if err != nil {
		return err
	}
	dst.Item = t
	return nil
}

func buildLevelTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.LevelTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 level 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 level 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newLevelTable(&data)
	if err != nil {
		return err
	}
	dst.Level = t
	return nil
}

func buildMissionTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.MissionTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 mission 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 mission 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newMissionTable(&data)
	if err != nil {
		return err
	}
	dst.Mission = t
	return nil
}

func buildParticleTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.ParticleTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 particle 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 particle 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newParticleTable(&data)
	if err != nil {
		return err
	}
	dst.Particle = t
	return nil
}

func buildPlayerLevelExpTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.PlayerLevelExpTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 player_level_exp 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 player_level_exp 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newPlayerLevelExpTable(&data)
	if err != nil {
		return err
	}
	dst.PlayerLevelExp = t
	return nil
}

func buildRewardTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.RewardTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 reward 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 reward 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newRewardTable(&data)
	if err != nil {
		return err
	}
	dst.Reward = t
	return nil
}

func buildRoleAttrMapTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.RoleAttrMapTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 role_attr_map 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 role_attr_map 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newRoleAttrMapTable(&data)
	if err != nil {
		return err
	}
	dst.RoleAttrMap = t
	return nil
}

func buildRoleLevelTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.RoleLevelTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 role_level 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 role_level 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newRoleLevelTable(&data)
	if err != nil {
		return err
	}
	dst.RoleLevel = t
	return nil
}

func buildRoleTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.RoleTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 role 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 role 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newRoleTable(&data)
	if err != nil {
		return err
	}
	dst.Role = t
	return nil
}

func buildShopTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.ShopTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 shop 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 shop 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newShopTable(&data)
	if err != nil {
		return err
	}
	dst.Shop = t
	return nil
}

func buildSkillBulletTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.SkillBulletTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 skill_bullet 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 skill_bullet 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newSkillBulletTable(&data)
	if err != nil {
		return err
	}
	dst.SkillBullet = t
	return nil
}

func buildSkillCardEffectTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.SkillCardEffectTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 skill_card_effect 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 skill_card_effect 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newSkillCardEffectTable(&data)
	if err != nil {
		return err
	}
	dst.SkillCardEffect = t
	return nil
}

func buildSkillCardTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.SkillCardTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 skill_card 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 skill_card 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newSkillCardTable(&data)
	if err != nil {
		return err
	}
	dst.SkillCard = t
	return nil
}

func buildSkillCardUpgradeTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.SkillCardUpgradeTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 skill_card_upgrade 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 skill_card_upgrade 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newSkillCardUpgradeTable(&data)
	if err != nil {
		return err
	}
	dst.SkillCardUpgrade = t
	return nil
}

func buildSkillCircleTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.SkillCircleTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 skill_circle 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 skill_circle 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newSkillCircleTable(&data)
	if err != nil {
		return err
	}
	dst.SkillCircle = t
	return nil
}

func buildSkillRectTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.SkillRectTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 skill_rect 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 skill_rect 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newSkillRectTable(&data)
	if err != nil {
		return err
	}
	dst.SkillRect = t
	return nil
}

func buildSkillSectorTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.SkillSectorTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 skill_sector 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 skill_sector 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newSkillSectorTable(&data)
	if err != nil {
		return err
	}
	dst.SkillSector = t
	return nil
}

func buildSkillTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.SkillTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 skill 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 skill 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newSkillTable(&data)
	if err != nil {
		return err
	}
	dst.Skill = t
	return nil
}

func buildSpawnGroupTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.SpawnGroupTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 spawn_group 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 spawn_group 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newSpawnGroupTable(&data)
	if err != nil {
		return err
	}
	dst.SpawnGroup = t
	return nil
}

func buildSpawnPointTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.SpawnPointTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 spawn_point 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 spawn_point 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newSpawnPointTable(&data)
	if err != nil {
		return err
	}
	dst.SpawnPoint = t
	return nil
}

func buildTalentEffectTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.TalentEffectTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 talent_effect 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 talent_effect 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newTalentEffectTable(&data)
	if err != nil {
		return err
	}
	dst.TalentEffect = t
	return nil
}

func buildTalentTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.TalentTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 talent 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 talent 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newTalentTable(&data)
	if err != nil {
		return err
	}
	dst.Talent = t
	return nil
}

func buildWeaponTable(raw []byte, mt ManifestTable, dst *Tables) error {
	var data configpb.WeaponTableData
	if err := unmarshalTable(raw, &data); err != nil {
		return fmt.Errorf("表 weapon 解析失败: %w", err)
	}
	if got := uint32(len(data.GetRows())); got != mt.Rows {
		return fmt.Errorf("表 weapon 行数 %d 与 manifest 声明 %d 不一致(疑似截断)", got, mt.Rows)
	}
	t, err := newWeaponTable(&data)
	if err != nil {
		return err
	}
	dst.Weapon = t
	return nil
}
