apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  namespace: pandora
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxUnavailable: 0, maxSurge: 1 }
  template:
    metadata:
      labels:
        istio.io/rev: PANDORA_ISTIO_REVISION_REQUIRED
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "21015"
    spec:
      serviceAccountName: pandora-inventory
      automountServiceAccountToken: false
      containers:
        - name: inventory
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop: ["ALL"]
