package gogen

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	// 夹具表注册(pandora.configtest.v1;TestFixtureRendering 经 DiscoverPackage 消费)
	_ "github.com/luyuancpp/pandora/proto/gen/go/pandora/configtest/v1"

	"github.com/luyuancpp/pandora/tools/configtable-gen/internal/tablegen"
)

func discover(t *testing.T) []tablegen.TableDef {
	t.Helper()
	defs, err := tablegen.Discover()
	if err != nil {
		t.Fatalf("Discover: %v", err)
	}
	return defs
}

// collapseSpaces 把连续空白折叠为单个空格(R4 复审:形状断言不得依赖 gofmt 的
// map/struct 对齐空格——表数量一变对齐宽度就变,断言随之无谓变红)。
func collapseSpaces(s string) string {
	fields := strings.Fields(s)
	return strings.Join(fields, " ")
}

// containsShape 空白不敏感的包含断言:want 与 got 都折叠连续空白后比较。
func containsShape(got []byte, want string) bool {
	return strings.Contains(collapseSpaces(string(got)), collapseSpaces(want))
}

func TestFilesShape(t *testing.T) {
	files, err := Files(discover(t))
	if err != nil {
		t.Fatalf("Files: %v", err)
	}
	tbl, ok := files["level_table.gen.go"]
	if !ok {
		t.Fatalf("缺 level_table.gen.go,产物: %v", keys(files))
	}
	for _, want := range []string{
		"// Code generated by configtable-gen; DO NOT EDIT.",
		"源表:关卡/g_关卡.xlsx",
		"type LevelTable struct",
		"func newLevelTable(data *configpb.LevelTableData)",
		"validateLevelRow(row)", // 依赖手写伴生钩子
		"func (t *LevelTable) ByID(key uint32)",
		"func (t *LevelTable) ByIDs(keys []uint32)",
		"func (t *LevelTable) RandOne()",
		"func (t *LevelTable) Where(",
		"func (t *LevelTable) First(",
	} {
		if !containsShape(tbl, want) {
			t.Errorf("level_table.gen.go 缺少 %q", want)
		}
	}
	reg, ok := files["tables.gen.go"]
	if !ok {
		t.Fatal("缺 tables.gen.go")
	}
	for _, want := range []string{
		"type Tables struct",
		"Level *LevelTable",
		"PlayerLevelExp *PlayerLevelExpTable",
		`"level": {protoName: "pandora.config.v1.LevelTableData", build: buildLevelTable}`,
		`"player_level_exp": {protoName: "pandora.config.v1.PlayerLevelExpTableData", build: buildPlayerLevelExpTable}`,
		"func buildLevelTable(raw []byte, mt ManifestTable, dst *Tables) error",
		"func buildPlayerLevelExpTable(raw []byte, mt ManifestTable, dst *Tables) error",
	} {
		if !containsShape(reg, want) {
			t.Errorf("tables.gen.go 缺少 %q", want)
		}
	}
}

// defByName 按表名取定义。不能用 defs[0]:Discover 按表名定序,新增一张字典序更靠前的表
// (如 item)就会把断言指向别的表,让本用例无谓变红。
func defByName(t *testing.T, defs []tablegen.TableDef, name string) tablegen.TableDef {
	t.Helper()
	for _, d := range defs {
		if d.Name == name {
			return d
		}
	}
	t.Fatalf("未发现配置表 %q", name)
	return tablegen.TableDef{}
}

func TestCompanionStubShape(t *testing.T) {
	defs := discover(t)
	stub, err := CompanionStub(defByName(t, defs, "level"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(stub), "func validateLevelRow(row *configpb.LevelRow) error") {
		t.Fatalf("伴生桩缺钩子: %s", stub)
	}
	if strings.Contains(string(stub), "DO NOT EDIT") {
		t.Fatal("伴生桩归人维护,不应带 DO NOT EDIT 头")
	}
}

// TestGeneratedFilesUpToDate 守护「生成代码与 proto 注解同步」:
// 改了 excel 注解 / 模板却没重跑生成器,或有人手改了 *.gen.go,这里失败。
func TestGeneratedFilesUpToDate(t *testing.T) {
	pkgDir := filepath.Join("..", "..", "..", "..", "pkg", "configtable")
	if _, err := os.Stat(pkgDir); err != nil {
		t.Skipf("pkg/configtable 不存在,跳过: %v", err)
	}
	files, err := Files(discover(t))
	if err != nil {
		t.Fatal(err)
	}
	for name, want := range files {
		got, err := os.ReadFile(filepath.Join(pkgDir, name))
		if err != nil {
			t.Errorf("读 %s 失败(新表生成后未落盘?): %v", name, err)
			continue
		}
		if !bytes.Equal(got, want) {
			t.Errorf("%s 与 proto 注解不同步,请重跑: go run ./tools/configtable-gen -tables <Table根目录>", name)
		}
	}
	// 每张表的伴生文件必须存在(桩由生成器首跑创建,之后归人维护)
	for _, def := range discover(t) {
		if _, err := os.Stat(filepath.Join(pkgDir, def.Name+".go")); err != nil {
			t.Errorf("缺伴生文件 %s.go: %v", def.Name, err)
		}
	}

	// bitindex 产物同步:状态文件 + dist 数据都在仓库,可完整重建比对
	repoRoot := filepath.Join("..", "..", "..", "..")
	for _, def := range discover(t) {
		if !def.BitIndex {
			continue
		}
		statePath := filepath.Join(repoRoot, "configtable", "bitindex_state", def.Name+".json")
		distPath := filepath.Join(repoRoot, "configtable", "dist", def.Name+".json")
		if _, err := os.Stat(distPath); err != nil {
			t.Skipf("dist 未生成,跳过 bitindex 比对: %v", err)
		}
		state, err := tablegen.LoadBitState(statePath, false)
		if err != nil {
			t.Fatalf("表 %s: %v(bit_index 表必须有状态文件)", def.Name, err)
		}
		raw, err := os.ReadFile(distPath)
		if err != nil {
			t.Fatal(err)
		}
		container, err := def.ParseJSON(raw)
		if err != nil {
			t.Fatal(err)
		}
		live, changed := state.Assign(def.RowIDs(container))
		if changed {
			t.Errorf("表 %s 位序状态落后于 dist 数据,请重跑生成器", def.Name)
		}
		want, err := BitIndexFile(def, live, state.BitCount())
		if err != nil {
			t.Fatal(err)
		}
		got, err := os.ReadFile(filepath.Join(pkgDir, def.Name+"_bitindex.gen.go"))
		if err != nil {
			t.Errorf("读 %s_bitindex.gen.go 失败: %v", def.Name, err)
			continue
		}
		if !bytes.Equal(got, want) {
			t.Errorf("%s_bitindex.gen.go 与状态/数据不同步,请重跑生成器", def.Name)
		}
	}
}

// TestFixtureRendering key/multi_key/fk/bit_index 注解的代码渲染(configtest 夹具包;
// render 内部 gofmt 即语法校验,字符串断言钉住 API 形状)。
func TestFixtureRendering(t *testing.T) {
	const testImport = "github.com/luyuancpp/pandora/proto/gen/go/pandora/configtest/v1"
	defs, err := tablegen.DiscoverPackage("pandora.configtest.v1")
	if err != nil {
		t.Fatalf("DiscoverPackage: %v", err)
	}
	var dungeon tablegen.TableDef
	for _, d := range defs {
		if d.Name == "test_dungeon" {
			dungeon = d
		}
	}

	tbl, err := TableFileFor(dungeon, testImport)
	if err != nil {
		t.Fatalf("TableFileFor: %v", err)
	}
	for _, want := range []string{
		"func (t *TestDungeonTable) ByCode(key string)",           // excel_key 唯一键
		"func (t *TestDungeonTable) ListByDifficulty(key uint32)", // excel_multi_key 索引
		"func (t *TestDungeonTable) ListBySceneId(key uint32)",    // excel_fk 隐含反查
		"唯一键 编码 取值重复",                                             // 加载期唯一键查重
	} {
		if !strings.Contains(string(tbl), want) {
			t.Errorf("dungeon 表代码缺少 %q", want)
		}
	}

	reg, err := RegistryFileFor(defs, testImport)
	if err != nil {
		t.Fatalf("RegistryFileFor: %v", err)
	}
	for _, want := range []string{
		"func validateCrossTables(dst *Tables) error",
		"dst.TestScene.Exists(v)", // 跨表兜底校验
		"为 0(必填外键)",               // required fk 拒 0
		"func (tb *Tables) TestDungeonSceneIdRow(row *configpb.TestDungeonRow) (*configpb.TestSceneRow, bool)",
		"func (tb *Tables) TestDungeonSceneIdRowByID(id uint32)",
	} {
		if !strings.Contains(string(reg), want) {
			t.Errorf("夹具注册代码缺少 %q", want)
		}
	}

	bit, err := BitIndexFile(dungeon, []tablegen.BitEntry{{ID: 10, Bit: 0}, {ID: 11, Bit: 1}}, 5)
	if err != nil {
		t.Fatalf("BitIndexFile: %v", err)
	}
	for _, want := range []string{
		"var testDungeonBitIndexMap = map[uint32]uint32{",
		"func TestDungeonBitIndex(id uint32) (uint32, bool)",
		"const TestDungeonBitCount uint32 = 5",
	} {
		if !strings.Contains(string(bit), want) {
			t.Errorf("位序映射代码缺少 %q", want)
		}
	}
}

// TestFilesDeterministic 生成产物字节级确定(重复跑无 git 噪音)。
func TestFilesDeterministic(t *testing.T) {
	defs := discover(t)
	a, err := Files(defs)
	if err != nil {
		t.Fatal(err)
	}
	b, err := Files(defs)
	if err != nil {
		t.Fatal(err)
	}
	for name := range a {
		if !bytes.Equal(a[name], b[name]) {
			t.Errorf("%s 生成不确定", name)
		}
	}
}

func keys(m map[string][]byte) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	return out
}
